import { AlertTriangle, CheckCircle2, RefreshCw } from "lucide-react";

import { StatusBadge } from "../components/ui/StatusBadge";
import { useAuth } from "../features/auth/AuthContext";
import { useWorkspaceRole } from "../features/auth/useWorkspaceRole";
import { useAlerts } from "../features/alerts/useAlerts";
import type { Alert } from "../features/alerts/api";
import type { StatusTone } from "../types";

const severityTone: Record<Alert["severity"], StatusTone> = {
  CRITICAL: "danger",
  HIGH: "danger",
  MEDIUM: "warning",
  LOW: "info",
  INFO: "neutral",
};

const statusTone: Record<Alert["status"], StatusTone> = {
  OPEN: "danger",
  ACKNOWLEDGED: "warning",
  RESOLVED: "success",
  IGNORED: "neutral",
};

export function AlertsPage() {
  const { isAuthenticated } = useAuth();
  const { alerts, isLoading, error, refresh, resolve } =
    useAlerts(isAuthenticated);
  const permissions = useWorkspaceRole();

  const openAlerts = alerts.filter((alert) => alert.status === "OPEN").length;

  return (
    <div className="space-y-6">
      <section className="flex flex-col gap-4 rounded-lg border border-slate-800 bg-slate-950/70 p-5 md:flex-row md:items-center md:justify-between">
        <div>
          <p className="text-xs font-medium uppercase tracking-wide text-cyan-300">
            Operational alerts
          </p>
          <h2 className="mt-2 text-xl font-semibold text-white">
            Data quality and pipeline signals
          </h2>
          <p className="mt-2 text-sm text-slate-500">
            Review automatic alerts generated by imports, health scoring and analytics.
          </p>
        </div>
        <button
          className="inline-flex items-center justify-center gap-2 rounded-md border border-slate-800 bg-slate-900 px-3 py-2 text-sm text-slate-200 transition hover:text-white"
          type="button"
          onClick={() => void refresh()}
        >
          <RefreshCw size={15} />
          Refresh
        </button>
      </section>

      <section className="grid gap-4 md:grid-cols-3">
        <SummaryCard label="Open alerts" value={String(openAlerts)} tone="danger" />
        <SummaryCard
          label="Critical signals"
          value={String(alerts.filter((alert) => alert.severity === "CRITICAL").length)}
          tone="warning"
        />
        <SummaryCard label="Total alerts" value={String(alerts.length)} tone="info" />
      </section>

      {error ? (
        <div className="rounded-lg border border-red-400/20 bg-red-400/10 p-4 text-sm text-red-100">
          {error}
        </div>
      ) : null}

      <section className="grid gap-4 xl:grid-cols-2">
        {alerts.map((alert) => (
          <AlertCard
            key={alert.id}
            alert={alert}
            canResolve={permissions.can("alerts:resolve")}
            onResolve={resolve}
          />
        ))}
      </section>

      {!isLoading && !alerts.length ? (
        <div className="rounded-lg border border-slate-800 bg-slate-950/70 px-5 py-10 text-sm text-slate-500">
          No active alerts. Your operational data is currently stable.
        </div>
      ) : null}
    </div>
  );
}

function AlertCard({
  alert,
  canResolve,
  onResolve,
}: {
  alert: Alert;
  canResolve: boolean;
  onResolve: (alertId: string) => Promise<void>;
}) {
  return (
    <article className="rounded-lg border border-slate-800 bg-slate-950/70 p-5">
      <div className="flex items-start justify-between gap-4">
        <div className="flex gap-3">
          <div className="mt-1 rounded-md border border-red-400/30 bg-red-400/10 p-2 text-red-100">
            <AlertTriangle size={17} />
          </div>
          <div>
            <div className="flex flex-wrap items-center gap-2">
              <StatusBadge label={alert.severity} tone={severityTone[alert.severity]} />
              <StatusBadge label={alert.status} tone={statusTone[alert.status]} />
            </div>
            <h3 className="mt-3 text-base font-semibold text-white">
              {alert.title}
            </h3>
            <p className="mt-2 text-sm leading-6 text-slate-400">
              {alert.message}
            </p>
          </div>
        </div>
        {alert.status === "OPEN" && canResolve ? (
          <button
            className="inline-flex shrink-0 items-center justify-center gap-2 rounded-md border border-emerald-400/30 bg-emerald-400/10 px-3 py-2 text-sm text-emerald-100 transition hover:border-emerald-300/50"
            type="button"
            onClick={() => void onResolve(alert.id)}
          >
            <CheckCircle2 size={15} />
            Resolve
          </button>
        ) : null}
      </div>
      <div className="mt-5 grid gap-3 border-t border-slate-800 pt-4 text-sm sm:grid-cols-2">
        <Meta label="Type" value={alert.type} />
        <Meta
          label="Triggered"
          value={new Date(alert.triggered_at).toLocaleString("en-US")}
        />
      </div>
    </article>
  );
}

function SummaryCard({
  label,
  value,
  tone,
}: {
  label: string;
  value: string;
  tone: StatusTone;
}) {
  return (
    <div className="rounded-lg border border-slate-800 bg-slate-950/70 p-5">
      <StatusBadge label={label} tone={tone} />
      <strong className="mt-3 block text-3xl font-semibold text-white">
        {value}
      </strong>
    </div>
  );
}

function Meta({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <p className="text-xs uppercase tracking-wide text-slate-500">{label}</p>
      <p className="mt-1 text-slate-300">{value}</p>
    </div>
  );
}
