import {
  AlertTriangle,
  CheckCircle2,
  Database,
  FileBarChart,
  ShieldCheck,
  UploadCloud,
} from "lucide-react";

import { OperationsChart } from "../components/charts/OperationsChart";
import { MetricCard } from "../components/ui/MetricCard";
import { StatusBadge } from "../components/ui/StatusBadge";
import type { AnalyticsOverview, RecentImportItem } from "../features/analytics/api";
import type { Metric } from "../types";

const statusTone = {
  COMPLETED: "success",
  PROCESSING: "info",
  FAILED: "danger",
  VALIDATING: "warning",
  PENDING: "neutral",
} as const;

const severityTone = {
  CRITICAL: "danger",
  HIGH: "warning",
  MEDIUM: "info",
  LOW: "neutral",
  INFO: "info",
} as const;

type DashboardPageProps = {
  overview: AnalyticsOverview | null;
  isLoading: boolean;
  error: string | null;
};

function buildMetrics(overview: AnalyticsOverview | null): Metric[] {
  const healthScore = overview?.average_data_health_score ?? 0;

  return [
    {
      label: "Active datasets",
      value: String(overview?.active_datasets ?? 0),
      detail: "Datasets currently available in this workspace",
      tone: "info",
      icon: Database,
    },
    {
      label: "Processed imports",
      value: String(overview?.processed_imports ?? 0),
      detail: "Completed import jobs from the live backend",
      tone: "success",
      icon: UploadCloud,
    },
    {
      label: "Average data health",
      value: `${healthScore.toFixed(1)}/100`,
      detail: "Quality score across active operational datasets",
      tone: healthScore >= 80 ? "success" : "warning",
      icon: ShieldCheck,
    },
    {
      label: "Critical alerts",
      value: String(overview?.critical_alerts ?? 0),
      detail: "Open critical alerts scoped to your organizations",
      tone: overview?.critical_alerts ? "danger" : "success",
      icon: AlertTriangle,
    },
    {
      label: "Generated reports",
      value: String(overview?.generated_reports ?? 0),
      detail: "PDF reports generated by your workspace",
      tone: "neutral",
      icon: FileBarChart,
    },
  ];
}

function formatRows(value: number) {
  return new Intl.NumberFormat("en-US").format(value);
}

function formatFinishedAt(importJob: RecentImportItem) {
  if (!importJob.finished_at) {
    return "Running";
  }

  return new Intl.DateTimeFormat("en-US", {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(new Date(importJob.finished_at));
}

export function DashboardPage({ overview, isLoading, error }: DashboardPageProps) {
  const metrics = buildMetrics(overview);
  const recentImports = overview?.recent_imports ?? [];
  const severityCounts = overview?.alerts_by_severity ?? [];

  return (
    <div className="space-y-6">
      {error ? (
        <div className="rounded-lg border border-red-400/30 bg-red-400/10 p-4 text-sm text-red-100">
          {error}
        </div>
      ) : null}

      <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">
        {metrics.map((metric) => (
          <MetricCard key={metric.label} metric={metric} />
        ))}
      </section>

      <section className="grid gap-6 xl:grid-cols-[minmax(0,1.55fr)_minmax(320px,0.85fr)]">
        <div className="rounded-lg border border-slate-800 bg-slate-950/70 p-5">
          <div className="mb-5 flex items-center justify-between gap-4">
            <div>
              <h2 className="text-base font-semibold text-white">
                Import throughput and quality
              </h2>
              <p className="mt-1 text-sm text-slate-500">
                Monthly processing volume compared with data health.
              </p>
            </div>
            <StatusBadge
              label={isLoading ? "Loading" : "Live API"}
              tone={isLoading ? "neutral" : "info"}
            />
          </div>
          <OperationsChart
            importsTimeseries={overview?.imports_timeseries}
            healthScoreTrend={overview?.health_score_trend}
          />
        </div>

        <div className="rounded-lg border border-slate-800 bg-slate-950/70 p-5">
          <div className="mb-5 flex items-center justify-between">
            <div>
              <h2 className="text-base font-semibold text-white">Data lineage</h2>
              <p className="mt-1 text-sm text-slate-500">
                Current path from raw file to decision surface.
              </p>
            </div>
            <CheckCircle2 className="text-emerald-300" size={18} />
          </div>
          <div className="space-y-3">
            {[
              "Raw file stored",
              "Import job registered",
              "Schema detected",
              "Records normalized",
              "Analytics snapshots",
              "Dashboard and PDF reports",
            ].map((item, index) => (
              <div key={item} className="flex items-center gap-3">
                <div className="flex h-7 w-7 items-center justify-center rounded-md border border-cyan-400/30 bg-cyan-400/10 text-xs text-cyan-100">
                  {index + 1}
                </div>
                <span className="text-sm text-slate-300">{item}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="grid gap-6 xl:grid-cols-[minmax(0,1.2fr)_minmax(320px,0.8fr)]">
        <div className="rounded-lg border border-slate-800 bg-slate-950/70">
          <div className="border-b border-slate-800 p-5">
            <h2 className="text-base font-semibold text-white">
              Latest import jobs
            </h2>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full min-w-[720px] text-left text-sm">
              <thead className="text-xs uppercase text-slate-500">
                <tr>
                  <th className="px-5 py-3 font-medium">File</th>
                  <th className="px-5 py-3 font-medium">Dataset</th>
                  <th className="px-5 py-3 font-medium">Status</th>
                  <th className="px-5 py-3 font-medium">Rows</th>
                  <th className="px-5 py-3 font-medium">Health</th>
                  <th className="px-5 py-3 font-medium">Finished</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800">
                {recentImports.map((item) => (
                  <tr key={item.id} className="hover:bg-slate-900/50">
                    <td className="px-5 py-4 font-medium text-slate-100">
                      {item.original_filename}
                    </td>
                    <td className="px-5 py-4 text-slate-400">
                      {item.dataset_name}
                    </td>
                    <td className="px-5 py-4">
                      <StatusBadge
                        label={item.status}
                        tone={statusTone[item.status]}
                      />
                    </td>
                    <td className="px-5 py-4 text-slate-300">
                      {formatRows(item.total_rows)}
                    </td>
                    <td className="px-5 py-4 text-slate-300">
                      {item.health_score.toFixed(1)}/100
                    </td>
                    <td className="px-5 py-4 text-slate-500">
                      {formatFinishedAt(item)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
            {!recentImports.length ? (
              <div className="border-t border-slate-800 px-5 py-8 text-sm text-slate-500">
                No import jobs yet. Create a dataset and upload a file to start
                generating operational intelligence.
              </div>
            ) : null}
          </div>
        </div>

        <div className="rounded-lg border border-slate-800 bg-slate-950/70">
          <div className="border-b border-slate-800 p-5">
            <h2 className="text-base font-semibold text-white">Open alerts</h2>
          </div>
          <div className="space-y-3 p-5">
            {severityCounts.map((alert) => (
              <article
                key={alert.severity}
                className="rounded-lg border border-slate-800 bg-slate-900/60 p-4"
              >
                <div className="mb-3 flex items-center justify-between gap-3">
                  <StatusBadge
                    label={alert.severity}
                    tone={severityTone[alert.severity]}
                  />
                  <span className="text-xs text-slate-500">Workspace</span>
                </div>
                <h3 className="text-sm font-semibold text-slate-100">
                  {alert.count} {alert.severity.toLowerCase()} alert
                  {alert.count === 1 ? "" : "s"}
                </h3>
                <p className="mt-2 text-sm leading-6 text-slate-400">
                  Live alert count grouped by severity from the backend.
                </p>
              </article>
            ))}
            {!severityCounts.length ? (
              <div className="rounded-lg border border-slate-800 bg-slate-900/60 p-4 text-sm text-slate-500">
                No active alerts. Your operational data is currently stable.
              </div>
            ) : null}
          </div>
        </div>
      </section>
    </div>
  );
}
